# Where the homeserver is located (client-server URL).
homeserverUrl: "https://matrix.org"

# The access token for the bot to use.
accessToken: "YOUR_TOKEN_HERE"

# The directory the bot should store various bits of information in
dataPath: "/data/storage"

# Where to complain about features
noticeRoom: "#riot-dev:matrix.org"

# Github API token from https://github.com/settings/tokens
githubToken: ""

