# Where the homeserver is located (client-server URL).
homeserverUrl: "https://matrix.org"

# The access token for the bot to use.
accessToken: "YOUR_TOKEN_HERE"

# The directory the bot should store various bits of information in
dataPath: "/data/storage"

# Where to complain about features
noticeRoom: "#riot-dev:matrix.org"

# Github API token from https://github.com/settings/tokens
# The token should have `read:org` enabled.
githubToken: ""

# Where the retro board is located (organization only)
projectOwner: "vector-im"

# The ID of the project. Can only be an organization project.
projectId: 1234

# The column name to search for in the project
columnName: "Actions"

# The date to start recurring from
startDate: "October 22, 2019"

# The number of weeks to recur beyond the date given
recurWeeks: 2

# The hour to send the action in
hour: 10

# The prefixes to ignore
ignorePrefixes:
 - '#'

# Map of human initials to user IDs
initials:
  TR: "@travis:t2l.io"
